### ISSUE TITLE
[Feature Request] Other shapes than circles

### ISSUE THREAD

**Issue by jlnrrg** [Apparence-io/pal-widgets#1]
First of all thanks for providing such a great package :smile:.

At this point in time the package seems to only support circles as outlines.
This creates a visually unpleasing experience when trying to wrap non round elements, see image attached.
It might be a great addition to support other Shapes/ and/or support a wrapping of the element.

![Screenshot from 2021-12-03 12-42-48](https://user-images.githubusercontent.com/77293597/144597273-ed2680bc-2cc5-44f4-8b41-d895bea8a1e7.png)

**Comment by g-apparence** [comment]
Hi, thank you for you kind words. 
That's a great suggestion. 
Will look to add some prebuilt shapes factories and maybe let you do one. 

Would this fit your needs ?

**Comment by jlnrrg** [comment]
I think the default flutter shapes do a great job already. 
So this would be more than sufficient (namely `RoundedRectangleBorder`)

As an inspiration, [onboarding_overlay](https://pub.dev/packages/onboarding_overlay) solved this quite good.

**Comment by g-apparence** [comment]
Yes,
point is that we are drawing them directly using canvas so we don't use these. 
(Our circle is drawing a hole and animating with 2 shadowed circles...). 

onboarding_overlay draws a shape directly.

**Comment by jlnrrg** [comment]
good to know, then I'd say the package would need to support a shape which can be wider than taller / taller than wider.
Something which a circle just can not support, so smth. like a Rectangle (preferably with rounded borders for esthetics) would be great.

**Comment by g-apparence** [comment]
Yep that's great idea, 
Basically, we could try doing the exact same animation but with rectangle on the exact bounds of the anchor.

**Comment by g-apparence** [comment]
Just played a little making this. 
Also had to refactor some code on the plugin. 
What do you think? @jlnrrg 

https://user-images.githubusercontent.com/48241546/145228482-89488753-19ff-46a1-8f13-4f8034b03e96.mp4

**Comment by jlnrrg** [comment]
I assume your child's padding is only vertical, then it makes sense.
Additionally it would require the possibility for rounded corners, but this already looks awesome :+1:

**Comment by g-apparence** [comment]
The padding comes from the bounds of the widgets. 
Flutter makes a larger touch area for buttons than it's drawn. As we use the bounds of the widget we got this little padding. 
Rounded corners can be great too yes

Also you can create your own painter factory to make custom drawing
